game.Words.register(0)
    .set(game.LanguageType.Chinese, "赔付表")
    .set(game.LanguageType.Vietnamese, "Bảng trả thưởng")
game.Words.register(1)
    .set(game.LanguageType.Chinese, "符号赔付表")
    .set(game.LanguageType.Vietnamese, "Giá trị trả thưởng cho biểu tượng")
game.Words.register(2)
    .set(game.LanguageType.Chinese, "百搭符号")
    .set(game.LanguageType.Vietnamese, "Biểu tượng Wild")
game.Words.register(3)
    .set(game.LanguageType.Chinese, "夺宝符号")
    .set(game.LanguageType.Vietnamese, "Biểu tượng Scatter")
game.Words.register(4)
    .set(game.LanguageType.Chinese, "神秘符号")
    .set(game.LanguageType.Vietnamese, "Biểu tượng Hộp Bí Ẩn")
game.Words.register(5)
    .set(game.LanguageType.Chinese, "·  百搭符号可替代除夺宝符号和神秘宝箱符号外的所有符号。")
    .set(game.LanguageType.Vietnamese, "·  Biểu tượng Wild thay thế cho tất cả các biểu tượngngoại trừ biểu tượng Scatter và biểu tượng Hộp Bí Mật")
game.Words.register(6)
    .set(game.LanguageType.Chinese, "·  百搭符号只会出现在第2，第3和第4轴上。")
    .set(game.LanguageType.Vietnamese, "·  Biểu tượng Wild chỉ xuất hiện trên các guồng 2, 3 hoặc4.")
game.Words.register(7)
    .set(game.LanguageType.Chinese, "神秘宝箱模式")
    .set(game.LanguageType.Vietnamese, "Tính năng Hộp Bí Ẩn")
game.Words.register(8)
    .set(game.LanguageType.Chinese, "·  神秘宝箱模式可以在主游戏的任何旋转中随机触发。")
    .set(game.LanguageType.Vietnamese, "·  Tính năng Hộp Bí Ẩn có thể kích hoạt ngẫu nhiên trênbất kỳ vòng quay trò chơi chính.")
game.Words.register(9)
    .set(game.LanguageType.Chinese, "·  神秘宝箱模式期间，5至10个神秘宝箱符号会出现在卷轴的任意位置上。")
    .set(game.LanguageType.Vietnamese, "·  Trong Tính năng Hộp Bí Ẩn, 5 đến 10 biểu tượng HộpBí Ẩn sẽ xuất hiện trên mọi vị trí trên các guồng quay.")
game.Words.register(10)
    .set(game.LanguageType.Chinese, "·  所有神秘宝箱符号都将揭示随机选择的一个符号(夺宝符号和百搭符号除外)，然后支付赢奖。")
    .set(game.LanguageType.Vietnamese, "·  Tất cả biểu tượng Hộp Bí Ẩn sẽ mở ra một biểu tượngđược chọn ngẫu nhiên (ngoại trừ biểu tượng Scatter vàbiểu tượng Wild ) và sau đó trả thưởng phần thắng.")
game.Words.register(11)
    .set(game.LanguageType.Chinese, "免费旋转模式")
    .set(game.LanguageType.Vietnamese, "Tính năng Vòng quay miễn phí")
game.Words.register(12)
    .set(game.LanguageType.Chinese, "·  当3、4或5个夺宝符号出现在卷轴的任意位置时，将触发免费旋转模式并分别获得8、10或15次免费旋转。")
    .set(game.LanguageType.Vietnamese, "·  3, 4 hoặc 5 biểu tượng Scatter xuất hiện ở bất kỳ vị trínào trên các guồng quay sẽ tặng 8, 10 hoặc 15 vòngquay miễn phí tương ứng.")
game.Words.register(13)
    .set(game.LanguageType.Chinese, "·  当免费旋转开始时，卷轴第三列的中间位置将会出现一个粘性符号，并将持续保留于整场免费旋转。")
    .set(game.LanguageType.Vietnamese, "·  Khi bắt đầu Tính năng Vòng quay miễn phí, một biểutượng kết dính sẽ xuất hiện ở giữa guồng thứ ba và sẽ ởvị trí đó trong toàn bộ phiên chơi vòng quay miễnphí.")
game.Words.register(14)
    .set(game.LanguageType.Chinese, "·  每次免费旋转，所有粘性符号将揭示随机选择的个符号(夺宝符号和百搭符号除外)。")
    .set(game.LanguageType.Vietnamese, "·  Tại mỗi vòng quay miễn phí, tất cả biểu tượng kết dínhsẽ mở ra một biểu tượng được chọn ngẫu nhiên (ngoạitrừ biểu tượng Scatter và biểu tượng Wild).")
game.Words.register(15)
    .set(game.LanguageType.Chinese, "·  当所有卷轴停止旋转时，若卷轴上任意符号与粘性符号相匹配，这些符号将在剩余的免费旋转中被转化为粘性符号。")
    .set(game.LanguageType.Vietnamese, "·  Khi tất cả guồng ngừng quay, mọi biểu tượng trên cácguồng quay khớp với biểu tượng kết dính sẽ đượcchuyển hóa thành một biểu tượng kết dính trong toànbộ các vòng quay miễn phí còn lại.")
game.Words.register(16)
    .set(game.LanguageType.Chinese, "·  免费旋转期间，卷轴上最多可出现15个粘性符号。")
    .set(game.LanguageType.Vietnamese, "·  Có thể có tối đa 15 biểu tượng kết dính trên các guồngquay trong Tính năng Vòng quay miễn phí.")
game.Words.register(17)
    .set(game.LanguageType.Chinese, "·  夺宝符号不会在免费旋转模式中出现。")
    .set(game.LanguageType.Vietnamese, "·  Biểu tượng Scatter không xuất hiện trong Tính năngVòng quay miễn phí.")
game.Words.register(18)
    .set(game.LanguageType.Chinese, "中奖线")
    .set(game.LanguageType.Vietnamese, "Dòng cược thắng")
game.Words.register(19)
    .set(game.LanguageType.Chinese, "·  只支付每条下注线中赢取最高的奖金。")
    .set(game.LanguageType.Vietnamese, "·  Chỉ trả cược thắng cao nhất trên mỗi dòng cược.")
game.Words.register(20)
    .set(game.LanguageType.Chinese, "·  中奖线奖金按照从最左至右转轴的顺序派发。")
    .set(game.LanguageType.Vietnamese, "·  Dòng cược sẽ thắng nếu các biểu tượng chiến thắngxuất hiện liên tiếp từ guồng quay ngoài cùng bên tráisang bên phải.")
game.Words.register(21)
    .set(game.LanguageType.Chinese, "·  所有中奖以现金显示。")
    .set(game.LanguageType.Vietnamese, "·  Tất cả tiền thắng cược được hiển thị bằng tiền mặt.")

game.Words.register(22)
    .set(game.LanguageType.Chinese, "游戏规则")
    .set(game.LanguageType.Vietnamese, "Luật chơi")
game.Words.register(23)
    .set(game.LanguageType.Chinese, "水果丛林")
    .set(game.LanguageType.Vietnamese, "Khu Rừng Vui Nhộn")
game.Words.register(24)
    .set(game.LanguageType.Chinese, "·  水果从林是一个5轴3行的视频老虎机游戏，编入了神秘宝箱符号，以及带有粘性符号的免费旋转。")
    .set(game.LanguageType.Vietnamese, "·  Khu Rừng Vui Nhộn là một trò chơi video slot (xèng)gồm 5 guồng quay, 3 hàng có các biểu tượng Hộp BíẨn và vòng quay miễn phí với các biểu tượng kếtdính.")
game.Words.register(25)
    .set(game.LanguageType.Chinese, "·  投注大小可以在“投注大小”选项中设定。")
    .set(game.LanguageType.Vietnamese, "·  Quy mô cược được đặt bằng bộ chọn “Quy môcược”.")
game.Words.register(26)
    .set(game.LanguageType.Chinese, "·  投注倍数可以在“投注倍数”选项中设定。")
    .set(game.LanguageType.Vietnamese, "·  Mức cược được đặt bằng bộ chọn “Mức cược”.")
game.Words.register(27)
    .set(game.LanguageType.Chinese, "·  投注总额可以在“投注总额”选项中设定。")
    .set(game.LanguageType.Vietnamese, "·  Số tiền cược được đặt bằng bộ chọn “Số tiền cược”.")
game.Words.register(28)
    .set(game.LanguageType.Chinese, "·  “现金钱包”用来显示下注者可用的现金余额。")
    .set(game.LanguageType.Vietnamese, "·  “Ví tiền mặt” hiển thị số tiền khả dụng để đặt cược")
game.Words.register(29)
    .set(game.LanguageType.Chinese, "·  “自动旋转”可以根据玩家所选择的回合数量自动进行游戏")
    .set(game.LanguageType.Vietnamese, "·  “Quay tự động” tự động chơi trò chơi theo số vòngquay đã chọn.")
game.Words.register(30)
    .set(game.LanguageType.Chinese, "·  中奖组合和奖金派发是根据“赔付表”进行的。")
    .set(game.LanguageType.Vietnamese, "·  Thắng kết hợp và trả thưởng được thực hiện theo“Bảng trả thưởng”.")
game.Words.register(31)
    .set(game.LanguageType.Chinese, "·  一条中奖线所得的奖励等同于显示在“赔付表”上的符号赔付值剩以投注大小和投注倍数。")
    .set(game.LanguageType.Vietnamese, "·  Tiền thắng cược theo dòng cược bằng giá trị hiển thịtrên “Bảng trả thưởng” nhân với kích cỡ cược vàmức cược.")
game.Words.register(32)
    .set(game.LanguageType.Chinese, "·  只支付每条下注线中赢取最高的奖金。")
    .set(game.LanguageType.Vietnamese, "·  Chỉ trả cược thắng cao nhất trên mỗi dòng cược")
game.Words.register(33)
    .set(game.LanguageType.Chinese, "·  中奖线奖金按照从最左至右转轴的顺序派发。")
    .set(game.LanguageType.Vietnamese, "·  Dòng cược sẽ thắng nếu các biểu tượng chiến thắngxuất hiện liên tiếp từ guồng quay ngoài cùng bên tráisang bên phải.")
game.Words.register(34)
    .set(game.LanguageType.Chinese, "·  不同中奖线上的奖金会被叠加。")
    .set(game.LanguageType.Vietnamese, "·  Cược thắng đồng thời trên các dòng cược khác nhauđược cộng dồn lại.")
game.Words.register(35)
    .set(game.LanguageType.Chinese, "·  所有中奖以现金显示。")
    .set(game.LanguageType.Vietnamese, "·  Tất cả tiền thắng cược được hiển thị bằng tiền mặt.")
game.Words.register(36)
    .set(game.LanguageType.Chinese, "·  白搭符号可替代除夺宝符号和神秘宝箱符号外的所有符号")
    .set(game.LanguageType.Vietnamese, "·  Biểu tượng Wild thay thế cho tất cả các biểu tượngngoại trừ biểu tượng Scatter và biểu tượng Hộp BíMật.")
game.Words.register(37)
    .set(game.LanguageType.Chinese, "·  百搭符号只出现在第2，第3和第4转轴上。")
    .set(game.LanguageType.Vietnamese, "·  Biểu tượng Wild chỉ xuất hiện trên các guồng 2, 3hoặc 4.")
game.Words.register(38)
    .set(game.LanguageType.Chinese, "·  免费旋转模式中投注大小和投注倍数和触发免费旋转模式时的参数保持一致。")
    .set(game.LanguageType.Vietnamese, "·  Tính năng Nhiều Vòng quay miễn phí được chơi ởkích cỡ cược và mức cược giống như vòng quay kíchhoạt tính năng Nhiều vòng quay miễn phí.")
game.Words.register(39)
    .set(game.LanguageType.Chinese, "神秘宝箱模式")
    .set(game.LanguageType.Vietnamese, "Tính năng Hộp Bí Ẩn")
game.Words.register(40)
    .set(game.LanguageType.Chinese, "·  神秘宝箱模式可以在主游戏的任何旋转中随机触发。")
    .set(game.LanguageType.Vietnamese, "·  Tính năng Hộp Bí Ẩn có thể kích hoạt ngẫu nhiêntrên bất kỳ vòng quay trò chơi chính.")
game.Words.register(41)
    .set(game.LanguageType.Chinese, "·  神秘宝箱模式期间，5至10个神秘宝箱符号会出现在卷轴的任意位置上。")
    .set(game.LanguageType.Vietnamese, "·  Trong Tính năng Hộp Bí Ẩn, 5 đến 10 biểu tượng HộpBí Ẩn sẽ xuất hiện trên mọi vị trí trên các guồng quay")
game.Words.register(42)
    .set(game.LanguageType.Chinese, "·  所有神秘宝箱符号都将揭示随机选择的一个符号(夺宝符号和百搭符号除外)，然后支付赢奖。")
    .set(game.LanguageType.Vietnamese, "·  Tất cả biểu tượng Hộp Bí Ẩn sẽ mở ra một biểu tượngđược chọn ngẫu nhiên (ngoại trừ biểu tượng Scattervà biểu tượng Wild ) và sau đó trả thưởng phần thắng.")
game.Words.register(43)
    .set(game.LanguageType.Chinese, "免费旋转模式")
    .set(game.LanguageType.Vietnamese, "Tính năng Vòng quay miễn phí")
game.Words.register(44)
    .set(game.LanguageType.Chinese, "·  当3、4或5个夺宝符号出现在卷轴的任意位置时，将触发免费旋转模式并分别获得8、10或15次免费旋转。")
    .set(game.LanguageType.Vietnamese, "·  3, 4 hoặc 5 biểu tượng Scatter xuất hiện ở bất kỳ vị trínào trên các guồng quay sẽ tặng 8, 10 hoặc 15 vòngquay miễn phí tương ứng.")
game.Words.register(45)
    .set(game.LanguageType.Chinese, "·  当免费旋转开始时，卷轴第三列的中间位置将会出现一个粘性符号，并将持续保留于整场免费旋转。")
    .set(game.LanguageType.Vietnamese, "·  Khi bắt đầu Tính năng Vòng quay miễn phí, một biểutượng kết dính sẽ xuất hiện ở giữa guồng thứ ba và sẽở vị trí đó trong toàn bộ phiên chơi vòng quay miễnphí.")
game.Words.register(46)
    .set(game.LanguageType.Chinese, "·  每次免费旋转，所有粘性符号将揭示随机选择的一个符号引(夺宝符号和百搭符号除外)。")
    .set(game.LanguageType.Vietnamese, "·  Tại mỗi vòng quay miễn phí, tất cả biểu tượng kết dínhsẽ mở ra một biểu tượng được chọn ngẫu nhiên (ngoạitrừ biểu tượng Scatter và biểu tượng Wild).")
game.Words.register(47)
    .set(game.LanguageType.Chinese, "·  当所有卷轴停止旋转时，若卷轴上任意符号与粘性符号相儿配，这些符号将在剩余的免费旋转中被转化为粘性符号。")
    .set(game.LanguageType.Vietnamese, "·  Khi tất cả guồng ngừng quay, mọi biểu tượng trên cácguồng quay khớp với biểu tượng kết dính sẽ đượcchuyển hóa thành một biểu tượng kết dính trongtoàn bộ các vòng quay miễn phí còn lại.")
game.Words.register(48)
    .set(game.LanguageType.Chinese, "·  免费旋转期间，卷轴上最多可出现15个粘性符号。")
    .set(game.LanguageType.Vietnamese, "·  Có thể có tối đa 15 biểu tượng kết dính trên cácguồng quay trong Tính năng Vòng quay miễn phí.")
game.Words.register(49)
    .set(game.LanguageType.Chinese, "·  夺宝符号不会在免费旋转模式中出现。")
    .set(game.LanguageType.Vietnamese, "·  Biểu tượng Scatter không xuất hiện trong Tính năngVòng quay miễn phí.")
game.Words.register(50)
    .set(game.LanguageType.Chinese, "主游戏")
    .set(game.LanguageType.Vietnamese, "Trò chơi chính")
game.Words.register(51)
    .set(game.LanguageType.Chinese, "旋转按钮")
    .set(game.LanguageType.Vietnamese, "Vòng quay")
game.Words.register(52)
    .set(game.LanguageType.Chinese, "·  单击后可在当前中奖线、投注大小和投注倍数下开始游戏。")
    .set(game.LanguageType.Vietnamese, "·  Chạm để bắt đầu quay ở Dòng cược, Lượngchip cược và Mức cược hiện tại.")
game.Words.register(53)
    .set(game.LanguageType.Chinese, "·  旋转过程中单击按钮或游戏区可以马上停止当前旋转。")
    .set(game.LanguageType.Vietnamese, "·  Chạm vào nút hoặc khu vực trò chơi trongmột vòng quay để dừng guồng quay.")
game.Words.register(54)
    .set(game.LanguageType.Chinese, "·  按下空格健，使用当前的投注线数、投注大小和投注倍数进行旋转。(仅适用于桌面版)")
    .set(game.LanguageType.Vietnamese, "·  Nhấn phím <Phím cách> để bắt đầu quay ởDòng cược, Lượng chip cược và Mức cượchiện tại. (chỉ khả dụng cho phiên bản máytính)")
game.Words.register(55)
    .set(game.LanguageType.Chinese, "·  按住空格键，将持续进行旋转，直到松开空格键。(仅适用于桌面版)")
    .set(game.LanguageType.Vietnamese, "·  Nhấn và Giữ phím <Phím cách> sẽ tiếp tụcvòng quay cho đến khi buông phím ra. (chỉkhả dụng cho phiên bản máy tính)")
game.Words.register(56)
    .set(game.LanguageType.Chinese, "停止按钮")
    .set(game.LanguageType.Vietnamese, "Dừng")
game.Words.register(57)
    .set(game.LanguageType.Chinese, "·  单击按钮停止旋转。在自动游戏模式，剩余旋转次数会显示在按钮中。")
    .set(game.LanguageType.Vietnamese, "·  Chạm để dừng Quay tự động. Số trên núthiển thị số vòng quay còn lại cho Quay tựđộng.")
game.Words.register(58)
    .set(game.LanguageType.Chinese, "旋转设置")
    .set(game.LanguageType.Vietnamese, "Tùy chọn Quay")
game.Words.register(59)
    .set(game.LanguageType.Chinese, "·  旋转速度可被设置为常速或极速(主游戏转轴的旋转时间将减少)")
    .set(game.LanguageType.Vietnamese, "·  Tốc độ Quay có thể đặt là Bình thường hoặcTurbo (giảm thời gian quay của các guồngtrong trò chơi chính).")
game.Words.register(60)
    .set(game.LanguageType.Chinese, "·  自动旋转可以根据选的次数进行自动游戏。")
    .set(game.LanguageType.Vietnamese, "·  Tính năng Quay tự động sẽ tự động chơitheo số vòng quay đã chọn.")
game.Words.register(61)
    .set(game.LanguageType.Chinese, "·  次数:点击所选次数进行自动游戏。")
    .set(game.LanguageType.Vietnamese, "·  Số Vòng Quay: Chạm để chọn số Vòng quaytự động.")
game.Words.register(62)
    .set(game.LanguageType.Chinese, "·  停止旋转单次赢得超过金额(玩家指定数值):当单次旋转赢得超过指定金额时，自动旋转将自动停止。")
    .set(game.LanguageType.Vietnamese, "·  Ngừng Tự Động Quay nếu một mức thắngvượt quá (giá trị được người chơi thiết lập):Tự Động Quay sẽ tự động tắt khi một mứcthắng vượt quá giá trị này.")
game.Words.register(63)
    .set(game.LanguageType.Chinese, "·  停止旋转余额增加超过金额(玩家指定数值):当余额的增幅超过指定金额时(与自动旋转开始前相比)，自动旋转将自动停止。")
    .set(game.LanguageType.Vietnamese, "·  Ngừng Tự Động Quay nếu số dư tăng (giá trịđược người chơi thiết lập): Quay tự động sẽtự động tắt khi số dư tăng thêm giá trị này(so với số dư khi bắt đầu Quay tự động).")
game.Words.register(64)
    .set(game.LanguageType.Chinese, "·  停止旋转余额减少超过金额(玩家指定数值):当余额的减幅超过指定金额时(与自动旋转开始前相比)，自动旋转将自动停止。")
    .set(game.LanguageType.Vietnamese, "·  Ngừng Tự Động Quay nếu số dư giảm (giá trịđược người chơi thiết lập): Tự Động Quay sẽtự động tắt khi số dư giảm đi giá trị này (sovới số dư khi bắt đầu Quay tự động).")
game.Words.register(65)
    .set(game.LanguageType.Chinese, "投注设置")
    .set(game.LanguageType.Vietnamese, "Tùy chọn Cược")
game.Words.register(66)
    .set(game.LanguageType.Chinese, "·  投注大小:拖动以选择投注大小。")
    .set(game.LanguageType.Vietnamese, "·  Lượng chip cược: Cuộn để chọn Lượng chipcược.")
game.Words.register(67)
    .set(game.LanguageType.Chinese, "·  投注倍数:拖动以选择投注倍数。")
    .set(game.LanguageType.Vietnamese, "·  Mức cược: Cuộn để chọn Mức cược.")
game.Words.register(68)
    .set(game.LanguageType.Chinese, "·  投注总额:拖动以选择投注金额。")
    .set(game.LanguageType.Vietnamese, "·  Số tiền cược: Cuộn để chọn Số tiền cược.")
game.Words.register(59)
    .set(game.LanguageType.Chinese, "·  最大投注:点击按钮可以把投注大小、投注倍数的数值调到最大。")
    .set(game.LanguageType.Vietnamese, "·  Cược tối đa: Chạm để đặt Lượng chip cược vàMức cược ở giá trị tối đa.")
game.Words.register(70)
    .set(game.LanguageType.Chinese, "极速旋转")
    .set(game.LanguageType.Vietnamese, "Tùy chọn Quay")
game.Words.register(71)
    .set(game.LanguageType.Chinese, "·  点击打开或关闭极速旋转。")
    .set(game.LanguageType.Vietnamese, "·  Tốc độ Quay có thể đặt là Bình thường hoặc Turbo")
game.Words.register(72)
    .set(game.LanguageType.Chinese, "更多")
    .set(game.LanguageType.Vietnamese, "Thêm")
game.Words.register(73)
    .set(game.LanguageType.Chinese, "·  点击进入“声音设置”、“赔付表”和“游戏规则”。")
    .set(game.LanguageType.Vietnamese, "·  Chạm để truy cập Âm thanh, Bảng trả thưởng, Quy tắc.")
game.Words.register(74)
    .set(game.LanguageType.Chinese, "更多设置")
    .set(game.LanguageType.Vietnamese, "Nhiều cài đặt hơn")
game.Words.register(75)
    .set(game.LanguageType.Chinese, "声音")
    .set(game.LanguageType.Vietnamese, "Âm thanh")
game.Words.register(76)
    .set(game.LanguageType.Chinese, "·  点击打开或关闭游戏声音。")
    .set(game.LanguageType.Vietnamese, "·  Chạm để BẬT hoặc TẮT âm thanh.")
game.Words.register(77)
    .set(game.LanguageType.Chinese, "赔付表")
    .set(game.LanguageType.Vietnamese, "Bảng trả thưởng")
game.Words.register(78)
    .set(game.LanguageType.Chinese, "·  显示中奖组合以及赔付表。")
    .set(game.LanguageType.Vietnamese, "·  Hiển thị các loại thắng kết hợp và bảng trảthưởng.")
game.Words.register(79)
    .set(game.LanguageType.Chinese, "规则")
    .set(game.LanguageType.Vietnamese, "Luật")
game.Words.register(80)
    .set(game.LanguageType.Chinese, "·  显示游戏规则和按键功能。")
    .set(game.LanguageType.Vietnamese, "·  Hiển thị luật chơi và các nút chức năng.")
game.Words.register(81)
    .set(game.LanguageType.Chinese, "关闭")
    .set(game.LanguageType.Vietnamese, "Đóng")
game.Words.register(82)
    .set(game.LanguageType.Chinese, "·  点击离开游戏， 并返回上一层。")
    .set(game.LanguageType.Vietnamese, "·  Chạm để thoát trò chơi và trở lại trang trước.")

game.Words.register(83)
    .set(game.LanguageType.Chinese, "旋转设置")
    .set(game.LanguageType.Vietnamese, "Tùy chọn Quay")
game.Words.register(84)
    .set(game.LanguageType.Chinese, "投注")
    .set(game.LanguageType.Vietnamese, "Cược")
game.Words.register(85)
    .set(game.LanguageType.Chinese, "余额")
    .set(game.LanguageType.Vietnamese, "Số dư")
game.Words.register(86)
    .set(game.LanguageType.Chinese, "赢奖")
    .set(game.LanguageType.Vietnamese, "thắng")
game.Words.register(87)
    .set(game.LanguageType.Chinese, "声音")
    .set(game.LanguageType.Vietnamese, "Âm thanh")
game.Words.register(88)
    .set(game.LanguageType.Chinese, "赔付表")
    .set(game.LanguageType.Vietnamese, "Bảng trả thưởng")
game.Words.register(89)
    .set(game.LanguageType.Chinese, "规则")
    .set(game.LanguageType.Vietnamese, "Luật")
game.Words.register(90)
    .set(game.LanguageType.Chinese, "退出")
    .set(game.LanguageType.Vietnamese, "Đóng")
game.Words.register(91)
    .set(game.LanguageType.Chinese, "投注总额")
    .set(game.LanguageType.Vietnamese, "Số tiền cược")
game.Words.register(92)
    .set(game.LanguageType.Chinese, "最大投注")
    .set(game.LanguageType.Vietnamese, "Cược tối đa")
game.Words.register(93)
    .set(game.LanguageType.Chinese, "确定")
    .set(game.LanguageType.Vietnamese, "Xác nhận")
game.Words.register(94)
    .set(game.LanguageType.Chinese, "旋转速度")
    .set(game.LanguageType.Vietnamese, "Tốc độ Quay")
game.Words.register(95)
    .set(game.LanguageType.Chinese, "自动旋转")
    .set(game.LanguageType.Vietnamese, "Quay tự động")
game.Words.register(96)
    .set(game.LanguageType.Chinese, "常速")
    .set(game.LanguageType.Vietnamese, "Bình thường")
game.Words.register(97)
    .set(game.LanguageType.Chinese, "极速")
    .set(game.LanguageType.Vietnamese, "Turbo")
game.Words.register(98)
    .set(game.LanguageType.Chinese, "开始自动旋转")
    .set(game.LanguageType.Vietnamese, "Bắt đầu Quay tự động")
game.Words.register(99)
    .set(game.LanguageType.Chinese, "3/4/5个夺宝符号可触发免费旋转。")
    .set(game.LanguageType.Vietnamese, "3/4/5 biểu tượng Scatter sẽ kích hoạt vòng quay miễn phí.")
game.Words.register(100)
    .set(game.LanguageType.Chinese, "百搭符号可替代除夺宝符号和神秘宝箱符号外的所有符号。")
    .set(game.LanguageType.Vietnamese, "Biểu tượng Wild thay thế cho tất cả các biểu tượng ngoại trừ biểu tượng Scatter và biểu tượng Hộp Bí Mật.")
game.Words.register(101)
    .set(game.LanguageType.Chinese, "金额不足!")
    .set(game.LanguageType.Vietnamese, "Không đủ GP")




