//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 线配置 KEY: id
	 */
	export class LabaLineList {
		id: number;
		/**
		 * 第1列行数
		 */
		col1RowNo: number;
		/**
		 * 第2列行数
		 */
		col2RowNo: number;
		/**
		 * 第3列行数
		 */
		col3RowNo: number;
		/**
		 * 第4列行数
		 */
		col4RowNo: number;
		/**
		 * 第5列行数
		 */
		col5RowNo: number;

		GetType(): string { return 'table.LabaLineList'; }
	}
}
