//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 特效返奖赔率
	 */
	export class LabaEffectMultiplyList {
		/**
		 * 特效类型
		 */
		effectType: number;
		/**
		 * 特效触发概率
		 */
		effectProbability: number;
		/**
		 * 特效赔率
		 */
		multipleList: string;

		GetType(): string { return 'table.LabaEffectMultiplyList'; }
	}
}
