//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 小玛丽外围图标 KEY: index
	 */
	export class MaryOutputIconList {
		/**
		 * 外围格子索引
		 */
		index: number;
		/**
		 * 物品ID
		 */
		itemId: number;

		GetType(): string { return 'table.MaryOutputIconList'; }
	}
}
