//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 特殊符号配置 KEY: specialSymbolType*0xFF + id
	 */
	export class TableSpecialSymbolConfig {
		/**
		 * 特殊符号类型
		 */
		specialSymbolType: number;
		/**
		 * 编号
		 */
		id: number;
		/**
		 * 数量
		 */
		num: number;
		/**
		 * 价值
		 */
		value: number;
		/**
		 * 特殊游戏参数
		 */
		gameArgs: number;

		GetType(): string { return 'table.TableSpecialSymbolConfig'; }
	}
}
