//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 玩法配置 KEY: level
	 */
	export class TableGameRuleConfigList {
		/**
		 * 等级
		 */
		level: number;
		/**
		 * 名称
		 */
		name: string;
		/**
		 * 返奖系数
		 */
		awardRatio: number;
		/**
		 * 免费游戏次数
		 */
		freeGameCount: number;
		/**
		 * 免费游戏追加次数
		 */
		freeGameCountAppend: number;
		/**
		 * 免费游戏特殊符号上限
		 */
		freeGameSpecialSymbolNumMax: number;
		/**
		 * AB模式切换系数
		 */
		abModeSwitchRatio: number;
		/**
		 * 无奖拼盘概率
		 */
		noAwardPinpanProp: number;
		/**
		 * 无奖首列连续概率
		 */
		noAward1ColProp: number;
		/**
		 * 无奖尾列连续概率
		 */
		noAward3ColProp: number;

		GetType(): string { return 'table.TableGameRuleConfigList'; }
	}
}
