//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 奖池特殊符号配置 KEY: id
	 */
	export class TableJackpotSpecialSymbolConfig {
		/**
		 * 编号
		 */
		id: number;
		/**
		 * 数量
		 */
		num: number;
		/**
		 * 价值
		 */
		value: number;
		/**
		 * 奖池返奖比率
		 */
		jackpotReturnPercent: number;
		/**
		 * 触发概率
		 */
		triggerProbability: number;
		/**
		 * 上限触发概率
		 */
		triggerProbabilityMax: number;
		/**
		 * 真假奖池
		 */
		isRealJackpot: boolean;
		/**
		 * 概率最大值
		 */
		triggerProbabilityAll: number;

		GetType(): string { return 'table.TableJackpotSpecialSymbolConfig'; }
	}
}
