//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 物品配置 KEY: id
	 */
	export class TableItemConfig {
		/**
		 * 物品编号
		 */
		id: number;
		/**
		 * 物品名称
		 */
		name: string;
		/**
		 * 免费游戏拆分次数
		 */
		freeGameSplitFrequency: number;

		GetType(): string { return 'table.TableItemConfig'; }
	}
}
