//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 玩法配置.xlsx SHEET: 小玛丽赔率 KEY: id*0xFF
	 */
	export class TableMaliMultiplyList {
		id: number;
		/**
		 * 返奖概率
		 */
		returnAwardProbability: number;
		/**
		 * 返奖赔率
		 */
		returnAwardMultiple: number;

		GetType(): string { return 'table.TableMaliMultiplyList'; }
	}
}
